# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyPage(object):
    def setupUi(self, MyPage):
        MyPage.setObjectName("MyPage")
        MyPage.resize(642, 619)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/Genç-STEM.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MyPage.setWindowIcon(icon)
        MyPage.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(:/new/arayuz.png);\n"
"")
        self.nesne = QtWidgets.QPushButton(MyPage)
        self.nesne.setGeometry(QtCore.QRect(220, 80, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.nesne.setFont(font)
        self.nesne.setAutoFillBackground(False)
        self.nesne.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(:/new/arayuz2.png);\n"
"color: rgb(25, 25, 25);")
        self.nesne.setObjectName("nesne")
        self.konum = QtWidgets.QPushButton(MyPage)
        self.konum.setGeometry(QtCore.QRect(220, 180, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.konum.setFont(font)
        self.konum.setAutoFillBackground(False)
        self.konum.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(:/new/arayuz2.png);\n"
"color: rgb(25, 25, 25);")
        self.konum.setObjectName("konum")
        self.cikis = QtWidgets.QPushButton(MyPage)
        self.cikis.setGeometry(QtCore.QRect(220, 280, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.cikis.setFont(font)
        self.cikis.setAutoFillBackground(False)
        self.cikis.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(:/new/arayuz2.png);\n"
"color: rgb(25, 25, 25);")
        self.cikis.setObjectName("cikis")

        self.retranslateUi(MyPage)
        QtCore.QMetaObject.connectSlotsByName(MyPage)

    def retranslateUi(self, MyPage):
        _translate = QtCore.QCoreApplication.translate
        MyPage.setWindowTitle(_translate("MyPage", "TEKNOFEST-GENÇSTEM"))
        self.nesne.setText(_translate("MyPage", "Nesne Tespiti"))
        self.konum.setText(_translate("MyPage", "Konum Tespiti"))
        self.cikis.setText(_translate("MyPage", "Çıkış"))
import back_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyPage = QtWidgets.QDialog()
    ui = Ui_MyPage()
    ui.setupUi(MyPage)
    MyPage.show()
    sys.exit(app.exec_())
